---
- name: "[CentOS] Fail if release is not supported"
  fail:
    msg: "[CentOS] The role is not designed for CentOS {{ansible_distribution_version}}"
  when:
    - ansible_distribution_major_version is version_compare('7', '!=')

- name: "[CentOS] Install required packages"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: "[CentOS] Add Docker yum repo key"
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: "[CentOS] Add Docker yum repo"
  yum_repository:
    name: docker-ce
    description: Docker-CE YUM repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: "[CentOS] Perform common tasks"
  include_tasks: "common.yml"