---
# Common setup tasks for all supported OS families

- name: "[Common] Install base dependencies"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ python_dev_package }}"
    - python-setuptools

- name: "[Common] Download get-pip.py"
  get_url: 
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp
    
- name: "[Common] Install pip"
  command: "python /tmp/get-pip.py"
    
- name: "[Common] Remove pip installer"
  file: 
    state: absent 
    path: /tmp/get-pip.py

# Required by the Ansible Docker module
- name: "[Common] Install docker-py"
  pip:
    name: docker-py
    state: latest

- name: "[Common] Install Docker CE package"
  package:
    name: docker-ce
    state: present

- name: "[Common] Ensure docker-ce is enabled at boot time"
  systemd: 
    name: docker
    enabled: yes

- name: "[Common] Start docker-ce service"
  systemd: 
    name: docker
    state: started

#- name: "Configure docker"
#  include: configure.yml
