---
- name: Fail if the OS is not supported
  fail:
    msg: "This role is not supported on {{ansible_distribution}}"
  when: 
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "CentOS"

- name: Include distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution|lower }}.yml"
    - "vars/{{ ansible_distribution|lower }}.yml"

# Include the relevant distro-specific task
- name: Perform setup for Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Perform setup for CentOS
  include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- meta: flush_handlers
