---
- name: "[Ubuntu] Fail if release is not supported"
  fail:
    msg: "[Ubuntu] The role is not designed for Ubuntu {{ansible_distribution_version}}"
  when:
    - ansible_distribution_version is version('14.04', '!=')
    - ansible_distribution_version is version('16.04', '!=')
    - ansible_distribution_version is version('18.04', '!=') 

- name: "[Ubuntu] Install required packages"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common

- name: "[Ubuntu] Add Docker apt repo key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 0EBFCD88

- name: "[Ubuntu] Add Docker apt repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "[Ubuntu] Perform common tasks"
  include_tasks: "common.yml"
