---
- name: "[Ubuntu] Fail if release is not supported"
  fail:
    msg="The role is designed only for Ubuntu 14.04"
  when: "( ansible_distribution_version | version_compare('14.04', '!=') ) and ( ansible_distribution_version | version_compare('16.04', '!=') )"

- name: "[Ubuntu] Add docker apt repo"
  apt_repository:
    repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state=present

- name: "[Ubuntu] Import the Docker repository key"
  apt_key:
    url=https://download.docker.com/linux/ubuntu/gpg
    state=present
    id=0EBFCD88

- name: "[Ubuntu] Force an apt cache refresh"
  apt: update_cache=yes
  changed_when: False

- name: "[Ubuntu] Perform common tasks"
  include: common.yml

